
apiVersion: v1
kind: Service
metadata:
  name: 2048-game-service
spec:
  type: NodePort
  selector:
    app: 2048-game
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # You can change this to any valid NodePort (30000–32767)
